Repository Yibarr/lolipop, pull requests merged in 2022-11, with the labels that each got.

#4 Styles for the principal page
  .gitignore
  public/index.html
  src/Presentation/App.css
  src/Presentation/App.tsx
  src/Presentation/index.css
Labels: enhancement

#5 ImgHome
  src/utils/img/imgHome.jpg
Labels: enhancement

#9 Navbar component added
  package-lock.json
  package.json
  src/Presentation/App.css
  src/Presentation/App.tsx
  src/Presentation/Components/Navbar/Navbar.tsx
  src/Presentation/Pages/Home/Home.css
  src/Presentation/Pages/Home/Home.tsx
  src/Presentation/index.css
  src/Resources/imgHome.jpg
  src/Tests/Home.test.tsx
  src/index.tsx
Labels: task

#11 SearchBar response interactions
  src/Data/API/Entity/SummonerAPIRequestEntity.ts
  src/Data/API/Entity/SummonerAPIResponse.ts
  src/Data/API/LeagueAPIDataManager.ts
  src/Data/LeagueAPIDataSource.ts
  src/Data/Repository/LeagueAPIServices.ts
  src/Data/Repository/LeagueRepository.ts
  src/Domain/Model/SummonerModel.ts
  src/Domain/UseCases/SummonerUseCase.ts
  src/Presentation/Components/Navbar/Navbar.tsx
  src/Presentation/Components/SearchBar/SearchBar.css
  src/Presentation/Components/SearchBar/SearchBar.tsx
  src/Presentation/Components/SearchBar/SearchBarViewModel.ts
  src/Presentation/Pages/Home/Home.css
  src/Presentation/Pages/Home/Home.tsx
  src/Presentation/Pages/Home/HomeViewModel.tsx
Labels: enhancement, task

#12 Navbar style enhancement
  src/Presentation/Components/Navbar/Navbar.tsx
  src/Presentation/Components/SearchBar/SearchBar.css
  src/Presentation/Components/SearchBar/SearchBar.tsx
  src/Presentation/Pages/Home/Home.css
  src/Presentation/Pages/Home/Home.tsx
  src/Presentation/Pages/Home/HomeViewModel.tsx
  src/Presentation/index.css
Labels: enhancement
